<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="MAIN" Id="{22a0f490-9a43-4d76-8f19-31a50310cd0f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	blueEdgeDetector : EdgeDetectorWithDoubleTap;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>