<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="SinusFunction" Id="{82bfeae4-7458-42c8-9888-ceb9443348a0}" SpecialFunc="None">
    <Declaration><![CDATA[	FUNCTION SinusFunction : REAL
VAR_INPUT
	r_Amplitude : REAL;
	r_Offset : REAL;
	r_Kreisfrequenz : REAL;
	r_Time : REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SinusFunction := r_Amplitude*SIN(r_Kreisfrequenz*r_Time) + r_Offset; ]]></ST>
    </Implementation>
    <LineIds Name="SinusFunction">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>