<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="Integrator" Id="{7444c4be-3c1a-431c-a15f-d1788f7f37e2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Integrator
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Integrator">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>