<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="DoSomeMath" Id="{d95a2906-c36e-4a3f-848e-54d4fa3976c7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM DoSomeMath
VAR_INPUT
	r_InputA : REAL ;
	r_InputB : REAL ;
END_VAR
VAR
	r_ResultAdd : REAL;
	r_ResultSub : REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[r_ResultAdd := AdditionFunction(r_InputA, r_InputB);
r_ResultSub := SubtractionFunction(r_InputA, r_InputB); 
	]]></ST>
    </Implementation>
    <LineIds Name="DoSomeMath">
      <LineId Id="5" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="11" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>