<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="SubtractionFunction" Id="{3f353174-a718-498d-8032-8da49980b23c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SubtractionFunction : REAL
VAR_INPUT
	i_valueA : REAL;
	i_valueB : REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SubtractionFunction := i_valueA - i_valueB;]]></ST>
    </Implementation>
    <LineIds Name="SubtractionFunction">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>