<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{f24976e0-536e-47c0-9e90-f6a02fca37e7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL_Pers.testPeristent := GVL_Pers.testPeristent +10;
GVL_Non_Pers.testNonPers := GVL_Non_Pers.testNonPers +10;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>